version: '3.8'

services:
  aleen-ia:
    build: .
    container_name: aleen-ia-app
    hostname: aleen-ia
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - REDIS_URL=rediss://default:ZWfqOUxs73mj80zl8xmsme8qNBr2RgiNj0Uo0T3xxPCu2OuIyFajsd5hPsUBlEUD@ocw00so4sg4o8g8ksscwokok:6380/0
      - REDIS_HOST=ocw00so4sg4o8g8ksscwokok
      - REDIS_PORT=6380
      - REDIS_PASSWORD=ZWfqOUxs73mj80zl8xmsme8qNBr2RgiNj0Uo0T3xxPCu2OuIyFajsd5hPsUBlEUD
      - REDIS_DB=0
      - PYTHON_AI_URL=https://ai-aleen.live.claudy.host
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_API_BASE_URL=${EVOLUTION_API_BASE_URL}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/webhook/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  # Volumes removidos pois Redis é externo
