version: '3.8'

services:
  # Node.js API
  aleen-node-api:
    build: .
    container_name: aleen-node-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - PYTHON_AI_BASE_URL=https://ai-aleen.live.claudy.host
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - aleen-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/webhook/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: aleen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aleen-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # Python AI Service (opcional - se quiser incluir)
  # python-ai:
  #   build:
  #     context: ../python
  #     dockerfile: Dockerfile
  #   container_name: aleen-python-ai
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ENVIRONMENT=production
  #   networks:
  #     - aleen-network
  #   restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  aleen-network:
    driver: bridge
